### ISSUE TITLE
未接来电的消息中的电话号码似乎没有被识别为电话号码

### ISSUE THREAD

**Issue by lan894734188** [telegram-sms/telegram-sms#11]
未接来电的消息中的电话号码似乎没有被识别为电话号码

[未接来电]
来电号码：xxxxxxxxxxx

**Comment by qwe7002** [comment]
这个问题是系统提供的来电号码中，没有国别码导致的。

Telegram的电话号码识别是 +<area code><phone number> 这样的，但系统并没有返回这个areacode过来，这就导致无法识别。

您可以查看以下问题：

https://stackoverflow.com/questions/40590683/how-to-make-phone-number-a-link-in-telegram-bot
