### ISSUE TITLE
是否可以将服务器暴露到设置?

### ISSUE THREAD

**Issue by ixiumu** [telegram-sms/telegram-sms#14]
是否可以在配置中修改目标服务器 api.telegram.org ,而不是重新编译,我看到你使用DoH来解决连通问题,其实telegram 的api服务器不校验来路和host头,我之前做的机器人一直是使用反向代理方式,这样对客户端网络环境没有要求,只需要修改一下连接的域名就可以了.

**Comment by qwe7002** [comment]
基于安全和隐私的考量，这个功能不会出现在今后的版本中。如果需要代理api.telegram.org,请尝试配置sni代理。

**Comment by qwe7002** [comment]
DOH并不是设计为保证连通性的。它是为了避免中间人攻击而设计的。sni代理可以避免数据包在转发的过程中被解包，这将保护数据包不被任何第三方获取。

https://github.com/dlundquist/sniproxy 这是一个sniproxy服务器，你也可以使用Nginx的Stream模块来实现这个功能

https://www.cnblogs.com/wshenjin/p/8719016.html

这是实践方法，stream在1.9.0被加入
