### ISSUE TITLE
Is it possible to relay phone calls to telegram? 有可能添加语音电话转播telegram的功能吗？

### ISSUE THREAD

**Issue by Neo-Zhixing** [telegram-sms/telegram-sms#15]
我不是太熟悉安卓的开发，和系统api的支持。但是，技术上是否有可能自动接电话并同时拨打一个telegram电话给用户？

I'm not too familiar with Android development, but is it technically possible to pick up phone calls automatically and relay that phone call to Telegram?

**Comment by qwe7002** [comment]
这个受制于权限，目前没有办法实现，我也在寻求这方面的方法

Sent from my iPhone

On Dec 28, 2019, at 17:13, Zhixing Zhang <notifications@github.com> wrote:

﻿

我不是太熟悉安卓的开发，和系统api的支持。但是，技术上是否有可能自动接电话并同时拨打一个telegram电话给用户？

I'm not too familiar with Android development, but is it technically possible to pick up phone calls automatically and relay that phone call to Telegram?

**Comment by qwe7002** [comment]
目前我自己在用的方法是，呼叫转移到其他号码，北美的号码我直接转移到GV了

Sent from my iPhone

On Dec 28, 2019, at 17:13, Zhixing Zhang <notifications@github.com> wrote:

﻿

我不是太熟悉安卓的开发，和系统api的支持。但是，技术上是否有可能自动接电话并同时拨打一个telegram电话给用户？

I'm not too familiar with Android development, but is it technically possible to pick up phone calls automatically and relay that phone call to Telegram?
