### ISSUE TITLE
Telegram sms app keeps waking

### ISSUE THREAD

**Issue by niclau** [telegram-sms/telegram-sms#16]
```
GitHub issue is used for bug reports only. For other issues such as feature request please submit it to [the forum](https://reall.uk), thank you.

You are welcome to submit an issue in English or Chinese. When you submit an issue in Chinese, it is recommended to attach an English translation for others to understand.

Github Issue只作为Bug收集使用。功能请求，使用问题请到 https://reall.uk 提交，谢谢。

欢迎您使用英语或者中文进行提交issue。当您使用中文提交issue的时候，建议附上英文翻译，以便他人理解。
```

**Describe the bug**
After configured and running this app, it keeps waking all the time.

**Expected behavior**
Just waking a few time when it needs to work.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: google nexus 5x
 - OS: android
 - Version 7.1.2

**Additional context**

Screenshots are here.
![Screenshot_20200105-085751](https://user-images.githubusercontent.com/575928/71780925-8bfefb00-3003-11ea-8462-182b53ecb1e9.png)
![Screenshot_20200105-085720](https://user-images.githubusercontent.com/575928/71780926-8c979180-3003-11ea-8410-515669e4e815.png)
![Screenshot_20200105-085708](https://user-images.githubusercontent.com/575928/71780927-8c979180-3003-11ea-8a0e-9bc25b13cf98.png)
![Screenshot_20200105-085658](https://user-images.githubusercontent.com/575928/71780928-8d302800-3003-11ea-96e5-af4453659f23.png)

**Comment by qwe7002** [comment]
我认为这个问题应该和您设备的电池寿命有关，由于隐私的考量，没有使用第三方的推送服务，直接调用了Telegram API。这个应用的三个后台进程会在后台持续唤醒响应来自你的信息。从记录来看，这个电量损耗只有69mah，相比起您手机电池2700mah(标称容量)来说并不多。

**Comment by niclau** [comment]
我还发现一个问题，对于发送者手机号码为英文的短信，app不会转发。
2020-01-06 09:34:19 GMT+08:00 [Google] Not a regular phone number.

**Comment by qwe7002** [comment]
我这里无法复现这个问题，这个通知是在sms_receiver.java的第174行，作用是判断这个号码是否为一个正常的号码，如果不是正常的，就不能加入回复列表内。这个操作是在执行结束转发的操作之后才进行的。

**Comment by qwe7002** [comment]
以及建议打开自动回落功能，因为有可能网络波动，导致无法正常连接到Telegram服务器
