### ISSUE TITLE
Android 4.2.2 support?

### ISSUE THREAD

**Issue by delphinuz** [telegram-sms/telegram-sms#17]
您好，
試著安裝到anroid 4.2.2機器，但安裝時出現套件剖析錯誤。

不知有無機會向下支援到4.2.2呢？讓舊手機也有使用，謝謝。

**Comment by qwe7002** [comment]
您可以使用 Telegram-sms-Compat，这是一个针对旧式机器的兼容版本

https://github.com/telegram-sms/telegram-sms-compat

这里是仓库地址

**Comment by delphinuz** [comment]
發現對應的ssr無法使用，有無機會加上個local port與http/socks支援呢？

**Comment by qwe7002** [comment]
这个你可以考虑在系统wifi设定中设置，我不会添加关于代理方面的功能，因为这不属于这个程序应该管辖的部分。

代理的设置可以参考以下文档

https://support.google.com/android/answer/9654714?hl=zh-Hans

**Comment by delphinuz** [comment]
目前4.2.2，使用telegram-sms-compat版本是沒問題的。
可以配合Kitsunebi 1.8.0。其餘的都有問題。

**Comment by qwe7002** [comment]
那看起来不错，主要是老系统的话，代理能用的的确是不多
