### ISSUE TITLE
Feature request: Support topics in telegram

### ISSUE THREAD

**Issue by kolsha** [telegram-sms/telegram-sms#33]
Hi!
Thanks for app, works perfectly.

I wonder, is it possible to support topics in telegram?

Telegram [has introduced](https://telegram.org/blog/topics-in-groups-collectible-usernames) them more than a year ago.

For me it seems to be a good fit for this.

**Comment by tangbao** [comment]
Hi, the coding is under test right now, and it will be merged into GitHub soon. We are waiting for our CI server to be back online. Thank you.

**Comment by Kolsha** [comment]
Hey folks,
Any updates on this?

**Comment by qwe7002** [comment]
Sorry, due to our internal Gitlab server failure, the new code has not been pushed up. I will fix this issue in the near future. The Topic function has almost been tested.

**Comment by qwe7002** [comment]
The new version already supports the Topic function.
