### ISSUE TITLE
[Suggestion] New Format of messages

### ISSUE THREAD

**Issue by MasedMSD** [telegram-sms/telegram-sms#41]
I would like to propose a new format for sending notices.
In Russian localization there is no space between "From" and sender's name and there are some problems, maybe should use another construction.

Instead of:
```markdown
[SIM1 SMS]
From: Undefined
Content: Bla bla bla, here is your code: 911228
```
We can use:
```markdown
<b>Type:</b> <code>SMS</code> - <code>SIM1</code>
<b>From:</b> <code>Undefined</code>

Bla bla bla, here is your code: <code>911228</code>
```

## What should it look like?
![image](https://github.com/user-attachments/assets/7bc8e560-c1eb-4bc3-939b-126bc925b8e8)

## Why?
1. Bold text in titles. At the UX level, it already helps the user to quickly see who sent and to which SIM.
2. Monospaced code in moments where there are names/codes. Also helps the user to quickly copy the code to paste in the app, author name for quick work with it
3. Removed Content field. It is useless, it is much more convenient to make \n\n after the "From" field and write the whole content of the message. The user will not need to be distracted

Also same thing for Battery, calls and etc.

**Comment by qwe7002** [comment]
Duplicate: 
https://github.com/telegram-sms/telegram-sms/issues/38 

I plan to implement a custom format function when I have time.
Thank you very much for your advice!
