### ISSUE TITLE
App Notification not working since master-8a5b7646-202207160902 version

### ISSUE THREAD

**Issue by ferlanero** [telegram-sms/telegram-sms#42]
The app notification is not working anymore since master-8a5b7646-202207160902 version. When I install this version, Telegram-SMS is correctly monitoring and sending to Telegram the app notifications I set in options. If I update to any newer version, Telegram-SMS stops monitoring app notifications although I had them set in options.

**Comment by qwe7002** [comment]
You can try the Prerelease version, maybe this problem has been fixed in the last rewrite.
