### ISSUE TITLE
需求：受限于网络的稳定性，断开连接时，请发送一个推送

### ISSUE THREAD

**Issue by dukoalad** [telegram-sms/telegram-sms#43]
.断开链接时请发送一条推送
“手机型号 **：**：** 断开了了连接”

**Comment by qwe7002** [comment]
我想了一下，我沒有什麼很好的辦法來監控手機斷開鏈接的情況。而且如果斷開鏈接之後你也難以獲得這個通知，感覺意義不是很大？

**Comment by dukoalad** [comment]
可以在设置中 ，user 自主设置轮询（30秒、60秒.....）查询是否联网状态，通知bot（可设置联网正常是否推送消息），没联网时，触发Bot自主发送一条消息tip
